### ISSUE TITLE
Penjelasan hal yang perlu di backend

### ISSUE THREAD

**Issue by sautmanurung1** [DwiSam/Career-Paths#7]
@DwiSam coba jelaskan lagi di issue ini apa yang perlu di backend nya 
soalnya aku lupa aja yang perlu di bagian backend nya dwi

**Comment by DwiSam** [comment]
1. login register
2. nge get soal dan jawabannya, jenis tipe kepribadian dan penjelasannya, jenis pekerjaan dan matkul
3. nyimpan hasil tesnya
4. nampilin hasil tes di dashboard admin

untuk tampilannya kurang lebih kaya gini [https://www.figma.com/file/Be49VCwFHqtuYdnrmDH5Ss/Website-Rekomendasi?node-id=0%3A1&t=Nl3tHCvasYolHh00-1](url)

**Comment by DwiSam** [comment]
untuk opsi dari pertanyannya nanti bisa diset ada type nya kaya gini ga? soalnya nanti ngitungnya berdasarkan type itu
1. Ketika masuk ke dalam lingkungan yang baru saya cenderung ...
    options: 
	a. lebih banyak mengamati, type: I 
      b. berkenalan dengan orang lain, type: E 
2. Saya lebih suka membuat tujuan yang bersifat ...
    options: 
	a. jangka panjang, type: N 
      b. jangka pendek, type: S 
3. Jika menghadapi dua pendapat yang berbeda, saya akan mengambil keputusan setelah ...
    options: 
	a. mengetahui sebab dan akibat dari suatu permasalahan, type: T 
	b. memahami cara pandang kedua pihak yang berbeda pendapat, type: F 
4. Saya lebih memilih untuk menjalani ...
    options: 
	a. kehidupan yang punya tujuan, type: J 
      b. kehidupan yang bebas, type: P

**Comment by sautmanurung1** [comment]
Ada list data mengenai masing masing type nya @DwiSam atau disesuaikan dengan data yang kemarin itu?

**Comment by DwiSam** [comment]
untuk pertanyaannya disini yaa 
[https://docs.google.com/document/d/1K1_sW6wx-uSBOw8lAYG43VfMoDNSQvX7aC268hf8snY/edit](url)

**Comment by sautmanurung1** [comment]
oke oke ntar aku kerjakan semua soalnya masih liburan hehehehehehe @DwiSam

**Comment by DwiSam** [comment]
amaan
